#! /usr/bin/expect

spawn gh auth login
expect "What account do you want to log into?"
send "GitHub.com\r"
expect "What is your preferred protocol for Git operations on this host?"
send "SSH\r"
expect "Generate a new SSH key to add to your GitHub account? (Y/n)"
send "Y\r"
expect " Enter a passphrase for your new SSH key (Optional)"
send "\r"
expect "Title for your SSH key:"
send "github\r"
expect "How would you like to authenticate GitHub CLI?"
send "Login with a web browser\r"

expect eof
